"""Python reference-module realization for vocabulary description bodies."""

from __future__ import annotations

from shikumi import Diagnostic, RealizationCheck, Realizer, SemanticView

from shikumi_devdoc.norms.vocabulary import Alias, Definition, Deprecated, Replacement, TermName, Title


_SOURCE_ATTRIBUTE = "__shikumi_devdoc_vocabulary_source__"
_TARGET_ATTRIBUTE = "__shikumi_devdoc_vocabulary_target__"


class PythonReferenceModuleRealizer(Realizer[str]):
    """Render a vocabulary semantic view as a human-readable Python reference module.

    The generated ``TERM_N`` classes are lightweight reference proxies.  Their
    docstrings contain the resolved term name and definition, while a private
    attribute points back to the canonical vocabulary class.  ``vocabulary_refs``
    understands that attribute and records the canonical class, so existing
    semantic identity is preserved.
    """

    def __init__(self, source_module: str) -> None:
        if not isinstance(source_module, str):
            raise TypeError("source_module must be a string")
        if not source_module:
            raise ValueError("source_module must not be empty")
        self.source_module = source_module

    def check(self, view: SemanticView) -> RealizationCheck:
        diagnostics: list[Diagnostic] = []
        roots = [item for item in view.entities if item.has(Title)]
        if len(roots) != 1:
            diagnostics.append(
                Diagnostic(
                    "Python vocabulary reference realization requires exactly one vocabulary root",
                    code="python.vocabulary_reference.document.required",
                )
            )

        entries = [item for item in view.entities if len(item.values(TermName)) == 1]
        if not entries:
            diagnostics.append(
                Diagnostic(
                    "Python vocabulary reference realization requires at least one term entry",
                    code="python.vocabulary_reference.entries.required",
                )
            )

        for entry in entries:
            if len(entry.values(Definition)) != 1:
                diagnostics.append(
                    Diagnostic(
                        "Python vocabulary reference realization requires exactly one definition per term",
                        code="python.vocabulary_reference.definition.required",
                        subject=entry.subject,
                    )
                )

        return RealizationCheck(view, tuple(diagnostics))

    def realize(self, view: SemanticView) -> str:
        entries = [
            item
            for item in view.entities
            if len(item.values(TermName)) == 1 and len(item.values(Definition)) == 1
        ]

        lines = [
            '"""Generated vocabulary term references.',
            "",
            f"Source: ``{self.source_module}``.",
            "",
            "Each ``TERM_N`` proxy exposes the human-readable term and definition in",
            "its docstring.  Pass this module to ``@vocabulary(...)`` and use the proxies",
            "with ``vocabulary_refs``.  Canonical vocabulary identity is retained internally.",
            "",
            "This file is generated by shikumi-devdoc.  Do not edit it manually.",
            '"""',
            "",
            "from __future__ import annotations",
            "",
            f"import {self.source_module} as _VOCABULARY_SOURCE",
            "",
            "_VOCABULARY = _VOCABULARY_SOURCE.VOCABULARY",
            f"{_SOURCE_ATTRIBUTE} = _VOCABULARY_SOURCE",
            "",
            "",
            "__all__ = [",
        ]

        for entry in entries:
            lines.append(f'    "{entry.node.name}",')
        lines.extend(["]", ""])

        for entry in entries:
            term_name = entry.values(TermName)[0]
            definition = entry.values(Definition)[0]
            details = [term_name, "", definition]
            aliases = entry.values(Alias)
            if aliases:
                details.extend(["", f"Aliases: {', '.join(aliases)}"] )
            if entry.values(Deprecated) == (True,):
                replacements = entry.values(Replacement)
                replacement_name = replacements[0] if replacements else None
                details.extend(["", "Deprecated." + (f" Use {replacement_name} instead." if replacement_name else "")])
            docstring = _python_docstring("\n".join(details))
            lines.extend(
                [
                    "",
                    f"class {entry.node.name}:",
                    f"    {docstring}",
                    "",
                    f"    {_TARGET_ATTRIBUTE} = _VOCABULARY.{entry.node.name}",
                ]
            )

        return "\n".join(lines).rstrip() + "\n"


def _python_docstring(text: str) -> str:
    """Return a readable Python string literal suitable as a class docstring."""

    for delimiter in ('"""', "'''"):
        if delimiter not in text and not text.endswith("\\"):
            return f"r{delimiter}{text}{delimiter}"
    return repr(text)
