"""Generated vocabulary term references.

Source: ``_internal.document_source.vocabulary.canonical``.

Each ``TERM_N`` proxy exposes the human-readable term and definition in
its docstring.  Pass this module to ``@vocabulary(...)`` and use the proxies
with ``vocabulary_refs``.  Canonical vocabulary identity is retained internally.

This file is generated by shikumi-devdoc.  Do not edit it manually.
"""

from __future__ import annotations

import _internal.document_source.vocabulary.canonical as _VOCABULARY_SOURCE

_VOCABULARY = _VOCABULARY_SOURCE.VOCABULARY
__shikumi_devdoc_vocabulary_source__ = _VOCABULARY_SOURCE


__all__ = [
    "TERM_1",
    "TERM_2",
    "TERM_3",
    "TERM_4",
]


class TERM_1:
    r"""外部情報

実現時に記述体の外部から与えられ、参照記号を通じて成果物へ取り込まれる情報。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_1

class TERM_2:
    r"""参照記号

外部情報または用語などを参照し、その値を実現結果へ取り込む位置を示す記号。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_2

class TERM_3:
    r"""用語参照体

用語の識別子、名称および説明を、人間がソースコード上から追跡できる形に実現したもの。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_3

class TERM_4:
    r"""表記維持

翻訳などによって文書の言語が変わる場合でも、その用語名の表記を変更せず使用することを示す情報。"""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_4
