"""Generated vocabulary term references.

Source: ``tests.fixtures.vocabulary_source``.

Each ``TERM_N`` proxy exposes the human-readable term and definition in
its docstring.  Pass this module to ``@vocabulary(...)`` and use the proxies
with ``vocabulary_refs``.  Canonical vocabulary identity is retained internally.

This file is generated by shikumi-devdoc.  Do not edit it manually.
"""

from __future__ import annotations

import tests.fixtures.vocabulary_source as _VOCABULARY_SOURCE

_VOCABULARY = _VOCABULARY_SOURCE.VOCABULARY
__shikumi_devdoc_vocabulary_source__ = _VOCABULARY_SOURCE


__all__ = [
    "TERM_1",
    "TERM_2",
]


class TERM_1:
    r"""Widget

A reusable widget."""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_1

class TERM_2:
    r"""InternalName

An implementation-only identifier."""

    __shikumi_devdoc_vocabulary_target__ = _VOCABULARY.TERM_2
